version: '3.1'
services:
    db:
        image: mysql:latest
        container_name: y9-mysql
        restart: always
        ports:
            - "3309:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 'Y9i-83204585'
            MYSQL_DATABASE: 'y9_public'
        volumes:
            - d:/docker-data/mysql:/var/lib/mysql

    redis:
        image: redis:latest
        container_name: y9-redis
        restart: always
        ports:
            - "7379:6379"
        command: redis-server --requirepass "y9i-83204585"
        volumes:
            - d:/docker-data/redis:/data
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: y9-zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 2181:2181
    kafka:
        image: wurstmeister/kafka
        container_name: y9-kafka
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_ADVERTISED_HOST_NAME=localhost
            - KAFKA_ADVERTISED_PORT=9092
            - KAFKA_LOG_DIRS=/kafka/log