plugins {
    id("net.risesoft.y9.java-conventions")
    id("net.risesoft.y9.docker")
    id("war")
    alias(libs.plugins.org.springframework.boot)
}

dependencies {
    api(platform(libs.spring.boot.bom))
    api(platform(libs.cas.server.bom))
    api(platform(libs.ojdbc.bom))
    
    api("org.apereo.cas:cas-server-core")
    api("org.apereo.cas:cas-server-core-authentication-api")
    api("org.apereo.cas:cas-server-core-authentication")
    api("org.apereo.cas:cas.server-support-person-directory")
    api("org.apereo.cas:cas-server-core-rest-api")
    api("org.apereo.cas:cas-server-core-web-api")
    api("org.apereo.cas:cas-server-core-util-api")
    api("org.apereo.cas:cas-server-core-services-api")
    api("org.apereo.cas:cas-server-core-services-registry")
    api(libs.googlecode.cqengine)
    api("org.apereo.cas:cas-server-core-services-authentication")
    api("org.apereo.cas:cas-server-core-tickets-api")
    api("org.apereo.cas:cas-server-core-api-ticket")
    api("org.apereo.cas:cas-server-core-validation-api")
    api("org.apereo.cas:cas-server-core-webflow-api")
    api("org.apereo.cas:cas-server-core-cookie-api")
    api("org.apereo.cas:cas-server-core-cookie")
    api("org.apereo.cas:cas.server.support-jpa-util")
    api("org.apereo.cas:cas.server.support-jpa-service-registry")
    api("org.apereo.cas:cas-server-core-authentication-attributes")
    api("org.springframework.security:spring-security-config")
    api("org.apereo.cas:cas-server-support-ldap-core")
    api(libs.hibernate.core)
    api("org.apereo.cas:cas-server-support-redis-core")
    api("org.apereo.cas:cas-server-support-redis-ticket-registry")
    api("org.apereo.cas:cas-server-support-session-redis")
    api("org.springframework.data:spring-data-redis")
    api(libs.lettucemod)
    api("org.apereo.cas:cas-server-core-api-logout")
    api("org.apereo.cas:cas-server-core-logout")
    api("org.apereo.cas:cas-server-core-logout-api")
    api("org.apereo.cas:cas-server-core-logging")
    api("org.springframework:spring-context-indexer")
    api(libs.uasparser)
    api(libs.jbcrypt)
    api(libs.google.zxing.core)
    api("org.apereo.cas:cas-server-support-token-tickets")
    api("org.apereo.cas:cas-server-support-token-core-api")
    api("org.apereo.cas:cas-server-support-oauth-webflow")
    api("org.apereo.cas:cas-server-support-oauth-api")
    api("org.apereo.cas:cas-server-support-oauth-core-api")
    api("org.apereo.cas:cas-server-support-oauth-core")
    api("org.apereo.cas:cas-server-support-oauth-services")
    api("org.apereo.cas:cas-server-support-pac4j-api")
    api("org.apereo.cas:cas.server.webapp-init")
    api("org.apereo.cas:cas-server-support-webconfig")
    api("org.apereo.cas:cas.server-webapp-starter-tomcat")
    api(project(":y9-digitalbase-common:risenet-y9boot-common-nacos"))
    api("org.springframework.boot:spring-boot-docker-compose")
    api(libs.mysql.connector.j)
    api(libs.mariadb.java.client)
    api(libs.postgresql)
    api("com.oracle.database.jdbc:ojdbc17")
    api(libs.kingbase.kingbase8)
    api(libs.kingbase.kesdialect.hibernate4)
    api(libs.dameng.dmdialect.hibernate62)
    api(libs.dameng.dmjdbcdriver18)

    providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")
}

description = "risenet-y9boot-webapp-sso-server"
val finalName = "sso"
jib.container.appRoot = "/usr/local/tomcat/webapps/${finalName}"

tasks.bootWar {
    archiveFileName.set("${finalName}.${archiveExtension.get()}")
}