/*
 * This file was generated by the Gradle "init" task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    id("buildlogic.docker")
    id("war")
    alias(libs.plugins.org.springframework.boot)
}

dependencies {
    api(project(":y9-digitalbase-module:y9-module-log:risenet-y9boot-support-log-web"))
    api(project(":y9-digitalbase-module:y9-module-log:risenet-y9boot-api-interface-log"))
    api(project(":y9-digitalbase-starter:risenet-y9boot-starter-security"))
    api(project(":y9-digitalbase-starter:risenet-y9boot-starter-sso-oauth2-resource"))
    api(project(":y9-digitalbase-starter:risenet-y9boot-starter-apisix"))
    api(project(":y9-digitalbase-starter:risenet-y9boot-starter-web"))
    api(project(":y9-digitalbase-common:risenet-y9boot-common-nacos"))
    api(libs.org.springframework.kafka.spring.kafka)
    api(libs.org.jxls.jxls)
    api(libs.org.jxls.jxls.poi)
    api(libs.org.jxls.jxls.jexcel)
    api(libs.org.jxls.jxls.reader)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.io.micrometer.micrometer.registry.prometheus)
    providedCompile(libs.jakarta.servlet.jakarta.servlet.api)
    providedRuntime(libs.org.springframework.boot.spring.boot.starter.tomcat)
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
}

description = "risenet-y9boot-webapp-log"

val finalName = "log"
jib.container.appRoot = "/usr/local/tomcat/webapps/${finalName}"

tasks.bootWar {
    archiveFileName.set("${finalName}.${archiveExtension.get()}")
}
