spring:
    application:
        name: sso
    session:
        store-type: redis
    mvc:
        problemdetails:
            enabled: true
    data:
        redis:
            username: default
            password: "12345678"
            host: localhost
            port: "6379"
    datasource:
        url: jdbc:postgresql://localhost:5432/authorization-server
        username: root
        password: "11111111"
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 20
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
        properties:
            jdbc:
                batch_size: 5
            hibernate:
                hbm2ddl:
                    charset_name: UTF-8
    sql:
        init:
            username: root
            password: "11111111"
            platform: postgresql
            continue-on-error: true
            separator: ";"
            encoding: utf-8
            mode: ALWAYS
            schema-locations:
                - optional:classpath:/sql/schema-${spring.sql.init.platform}.sql
            data-locations: ""
    security:
        oauth2:
            client:
                registration:
                    github-idp:
                        provider: github
                        client-id: github-client-id
                        client-secret: github-client-secret
                        scope: user:email, read:user
                        client-name: Sign in with GitHub
                provider:
                    github:
                        user-name-attribute: login
server:
    port: 9000
    forward-headers-strategy: FRAMEWORK
    servlet:
        context-path: /sso
        encoding:
            charset: UTF-8
            enabled: true
            force: true
            force-request: true
            force-response: true
        session:
            cookie:
                http-only: true
                secure: false
            timeout: 300
            tracking-modes: COOKIE
    shutdown: graceful
    ssl:
        enabled: false
    tomcat:
        accesslog:
            enabled: true
            pattern: '%t %a "%r" %s (%D ms)'
            suffix: .log
        additional-tld-skip-patterns: '*.jar'
        background-processor-delay: 0s
        basedir: build/tomcat
        connection-timeout: PT20S
        max-http-form-post-size: 2097152
        remoteip:
            port-header: X-Forwarded-Port
            protocol-header: X-Forwarded-Proto
            protocol-header-https-value: https
            remote-ip-header: X-FORWARDED-FOR
        threads:
            max: 400
            min-spare: 10
        uri-encoding: UTF-8
logging:
    level:
        root: INFO
        org.springframework.web: INFO
        org.springframework.security: debug
        org.springframework.security.oauth2: debug