cas:
    audit:
        engine:
            enabled: false
            numberOfDaysInHistory: 30
            useServerHostAddress: true
        redis:
            enabled: false
            useSsl: false
            host: "localhost"
            port: 6379
            database: 12
            username: default
            password: "111111"
            timeout: "PT60S"
            pool:
                enabled: true
                testWhileIdle: true
                maxActive: 20
                maxIdle: 5
                maxWait: 1000
                minIdle: 1
    authn:
        accept:
            enabled: false
        throttle:
            failure:
                #在上述时间段内允许的失败登录尝试次数
                threshold: 1
                #时间范围
                rangeSeconds: 3
                throttleWindowSeconds: "PT600S"
        oauth:
            crypto:
                encryption:
                    key: x_kBoXCREKfjPvCe5UCm6M_HfdkrsZwx2dq47uUu8TPPa_2QT80rF4j_lhleUIgwB43kkeAjjJp7rbp51Tm3iw
                    keySize: 512
                signing:
                    key: y_0BeZ5XmwzJ-H6CdnXAcH6cgUnrYpPZ7BD-_ug5kSt_Xc0Gubi6yuk6Zy7h9iK_5X909b2mVdiShWOctSCofg
                    keySize: 512
            refreshToken:
                timeToKillInSeconds: P14D
            code:
                timeToKillInSeconds: 600
                numberOfUses: 1
            access-token:
                timeToKillInSeconds: PT2H
                maxTimeToLiveInSeconds: PT8H
                createAsJwt: false
                crypto:
                    enabled: true
                    encryptionEnabled: true
                    signingEnabled: true
                    encryption:
                        key: kXfCSPsgzAJRD4yDrGOiOpubDEoJ7LlR2C_MADMqloPIqUPHGTv4RCEHuKvlJVFza2X2Cri35g7MutWcvzdkRA
                        keySize: 512
                    signing:
                        key: 0ND7_TDKBDl7Wx2yMBO608RyBTDe1FsT4_PmC59-rwKx9sv37lUTtP5p_7miiEuZvxBN6VZGjUM5thbtwVDMIg
                        keySize: 512
            grants:
                resourceOwner:
                    requireServiceHeader: true
            core:
                userProfileViewType: FLAT
                bypassApprovalPrompt: true
            session-replication:
                cookie:
                    crypto:
                        encryption:
                            key: 4KiqcYVJHlMEgESk0FGFiPM4aq_0HaWbRwB4wwzMWJncP9sx1h5X2jQpr4n0IhpWs-xD0Yuki7HBOSHXfofQ6Q
                        signing:
                            key: vpfJFaaSLDudc5Gj25_Uy-xhh-AJmCByeJQDweZr-qMlf2Cov9DqFPghrxm-IA1OcftkED8c99rilt-VzwU1Dg
                    secure: false
                    path: /sso/
                    sameSitePolicy: Lax
        token:
            crypto:
                encryption:
                    key: vM-BXOlGHTSZ3MbiUSRxMH1mY75pfZa84s0uOpqShfU4sj9k6-vc2DAzl8-iFep6oOf1OcBn28shK2lpRMgJxw
                    keySize: 512
                signing:
                    key: FkK7xwk6Ol5pnO9mEwB6prQT5mS5X7hVpUToofTgEzFkDqHpWdy-XwfXA_2l6v4Ya3ZYwEvbTvnMLh21mfjh_w
                    keySize: 512

    httpClient:
        allowLocalUrls: true
        hostNameVerifier: none
    httpWebRequest:
        header:
            xframe: false
            xframeOptions: SAMEORIGIN
            #contentSecurityPolicy: 'frame-ancestors http://localhost:* http://127.0.0.1:* http://192.168.56.1:*'
        cors:
            enabled: true
            allowCredentials: true
            allowHeaders: "*"
            allowMethods: "*"
            allowOriginPatterns: "*"
            maxAge: 36000
    locale:
        defaultValue: zh_CN
    theme:
        defaultThemeName: y9-apereo
        paramName: theme
    messageBundle:
        useCodeMessage: true
        fallbackSystemLocale: true
    view:
        #当service参数为空时，利用defaultRedirectUrl
        defaultRedirectUrl: http://localhost:7070/home
        #当defaultRedirectUrl为空、并且service参数为空时，自动计算service
        authorizedServicesOnSuccessfulLogin: true
    webflow:
        crypto:
            enabled: true
            encryption:
                key: R2wxx0EpHUz_3ZbDEovE3w
                keySize: 16
            signing:
                key: BEAHMw9OS4eQ2jxav4S1iDSkebnC4l5sKMGget-yhbgut1aH6prVqGLNex5PVAXqT7lSl1bzV_OOu8OcgH22EA
                keySize: 512
    logout:
        confirm-logout: false
        follow-service-redirects: true
        # redirect-parameter: "service"
        # redirect-url: http://localhost:7055/sso/login
    slo:
        asynchronous: false
    server:
        name: http://localhost:7055
        prefix: http://localhost:7055/sso
    service-registry:
        cache:
            duration: PT8H
            cacheSize: 10000
            initialCapacity: 1000
        core:
            # 建议仅用于测试（集群部署时需考虑 service.json 的同步，使用 jpa-service-registry 即可）
            initFromJson: false
        json:
            location: classpath:/services
            watcherEnabled: true
        jpa:
            enabled: true
            dialect: org.hibernate.dialect.MySQLDialect
            driver-class: com.mysql.cj.jdbc.Driver
            ddl-auto: update
            url: jdbc:mysql://localhost:3306/y9_public?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
            user: root
            password: '111111'
            idleTimeout: PT10M
            leakThreshold: 0
            autocommit: true
        schedule:
            enabled: true
            repeatInterval: "PT30M"
            startDelay: "PT2M"
    tgc:
        crypto:
            enabled: true
            encryption:
                key: xqn4eyW7zupUxhypdcA-gzGt_8eckMB0Im0EUFI0pCzfKdZv5rpSMN1ZNbt4kQjaV8uFksXYtCM7OSAMGj7g6Q
                keySize: 512
            signing:
                key: ILD_gwFETInK1hNxOkQfMLSQ2T310e49M7fg2lnv03ZyiQ4CdzsomEcHESLzB_ZkRYhQir-lA3qzVmeMZEgZcQ
                keySize: 512
        httpOnly: true
        maxAge: -1
        name: TGC
        path: /sso/
        pinToSession: true
        rememberMeMaxAge: P14D
        secure: false
        sameSitePolicy: Lax
    ticket:
        trackDescendantTickets: true
        crypto:
            enabled: false
            encryption:
                key: td7YCc3pFG-uPSIDIp-RbDScqfpY1CfrJgL22ZuJOE4odlrf3p980twHJnhyqmToV1lMX4TrjFdNMRWOw7kM5w
                keySize: 512
            signing:
                key: wzeJhwyCK0QeyF57MN2zVm35yaC7yxEj8N9BAqfFJIEep4B8mTVDdB7iW0vNLsRW5sRU-36eNKwtYrIxVsIBPQ
                keySize: 512
        registry:
            cleaner:
                schedule:
                    enabled: true
                    startDelay: "PT15S"
                    repeatInterval: "PT30M"
            redis:
                enabled: true
                useSsl: false
                host: "localhost"
                port: 6379
                database: 13
                username: default
                password: "111111"
                timeout: "PT60S"
                pool:
                    enabled: true
                    testWhileIdle: true
                    maxActive: 20
                    maxIdle: 5
                    maxWait: 1000
                    minIdle: 1
                crypto:
                    enabled: true
                    encryption:
                        key: "6vJAg4gWORY0f8dF5XIc8Q"
                        keySize: 16
                    signing:
                        key: "CzPeT3D2l7C-dwR2LfV9DFHrwmPGXCSsEReZeTn76xiWNU45De8s1CAdPNXovoBpEilbeTY1PkwPQuMxZdN4mQ"
                        keySize: 512
        st:
            maxLength: 50
            numberOfUses: 10
            timeToKillInSeconds: 600
        tgt:
            primary:
                maxTimeToLiveInSeconds: 28800
                timeToKillInSeconds: 7200
            core:
                maxLength: 50
            rememberMe:
                enabled: true
                timeToKillInSeconds: 28800
                #supportedUserAgents:
                #supportedIpAddresses: 127.0.0.1,0:0:0:0:0:0:0:1
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 7055
    servlet:
        context-parameters:
            isLog4jAutoInitializationDisabled: true
        context-path: /sso
        encoding:
            charset: UTF-8
            enabled: true
            force: true
            force-request: true
            force-response: true
        session:
            cookie:
                http-only: true
                secure: false
            timeout: 300
            tracking-modes: COOKIE
    shutdown: graceful
    ssl:
        enabled: false
    tomcat:
        accesslog:
            enabled: true
            pattern: '%t %a "%r" %s (%D ms)'
            suffix: .log
        additional-tld-skip-patterns: '*.jar'
        background-processor-delay: 0s
        basedir: build/tomcat
        connection-timeout: PT20S
        max-http-form-post-size: 2097152
        remoteip:
            port-header: X-Forwarded-Port
            protocol-header: X-Forwarded-Proto
            protocol-header-https-value: https
            remote-ip-header: X-FORWARDED-FOR
        threads:
            max: 400
            min-spare: 10
        uri-encoding: UTF-8
spring:
    application:
        name: sso
    cloud:
        nacos:
            config:
                enabled: false
                group: DEFAULT_GROUP
                namespace: local
                server-addr: http://localhost:8848
                username: nacos
                password: ${NACOS_PASSWORD:111111}
            discovery:
                enabled: false
        compatibility-verifier:
            enabled: false
    config:
        import:
            - optional:nacos:sso.yml
    docker:
        compose:
            enabled: false
            file: docker-dev.yml
    data:
        redis:
            database: 8
            host: localhost
            port: 6379
            username: default
            password: '11111'
            ssl:
                enabled: false
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 8
                    max-wait: -1
                    min-idle: 1
    jmx:
        enabled: false
    session:
        timeout: 3600
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: false
        lazy-initialization: false
    security:
        user:
            name: y9admin
            password: risesoft
    thymeleaf:
        cache: true
        mode: HTML
        encoding: UTF-8
        #prefix: classpath:/templates/
        #suffix: .html
        template-resolver-order: 100
y9:
    common:
        logBaseUrl: http://localhost:7055/log
    internalIp: 192.168.x.x,10.0.x.x,172.20.x.x
    login:
        casLoginView: "casLoginView-y9-v3.0"
        credentialPropsOptional: "screenDimension,userAgent,systemName,clientIp,clientMac,clientDiskId,clientHostName,deptId,positionId,pwdEcodeType"
        #kafka , jpa
        loginInfoSaveTarget: kafka
        encryptionRsaPublicKey: 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC6DvO5m7p1Of/IkPwMRdQK7tx4wZKrbmVj2aqhlX5z+McbxeiP1XgwpiFINxigtXqU49rtCb1eyUafD4lIYZ399Z5TAZeD3kH+ggdP6xRr0G7+u1UE9qgoLXPOugZsABwSOq5w9v6qGUAY8U3doLDkjCueMbEeGG96FjqaaMLckwIDAQAB'
        encryptionRsaPrivateKey: 'MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALoO87mbunU5/8iQ/AxF1Aru3HjBkqtuZWPZqqGVfnP4xxvF6I/VeDCmIUg3GKC1epTj2u0JvV7JRp8PiUhhnf31nlMBl4PeQf6CB0/rFGvQbv67VQT2qCgtc866BmwAHBI6rnD2/qoZQBjxTd2gsOSMK54xsR4Yb3oWOppowtyTAgMBAAECgYACb5OtSGamhj3dCFjkaD2gbwQf6Jjc+bMGHaFoQCbJqeYhbPPgfjD2ohYpdd8yq22RaXJCTDBYf1YXWwK3GeARn19tYnJodqspAya3jyfSFY+IRDQ2kQ/59w1VmBiOtJsUJG4va2Bz9SRfLZuXwOyznjKk7BE89Anb3ici6u6HYQJBAONiagv+Kc8dkxoip1NWYVFjCWNHTejWTgLLgVDZi1jep/8Xx5d5E1aewcvPCJRz8A7hYEY5Uc8Mt9PB6NhLedkCQQDReSXdMdg+/lLYwdX7lRfPH7PIGNK4UwmZQ0LW7fsoy8/TD9gMnQ9sAVHILKxQuhubDHGfonVhA08WA2nvgzpLAkEA0hMmbpYPAm8MbOT/OhtgJdUd4z8JV8hGooZpnsyd1SlAhIjvuZ3+o9Rgr29DOgQzEUxfqgFi96uEWnuYJ9zzYQJBAK0SL5qmiEjj0IeO/8Gx2c4kH2KAP/pTgWbEEAGM9ysp2jhEqvkg+5D9Nhjx8B1y50Qf7/E5RUo2da12fJyMDCkCQDjBuq+dssaPGs36oijHBxzJmeaFR6vmKBUaiwYJEHg2ayi3r3/dHRrqYxXC2wblxOhkytUl/R1DErHztHHm878='
