/*
 * This file was generated by the Gradle "init" task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("net.risesoft.y9.java-conventions")
    id("net.risesoft.y9.lombok")
}

dependencies {
    api(platform(libs.spring.boot.bom))
    //api(platform(libs.spring.cloud.alibaba.bom))

    api(project(":y9-digitalbase-common:risenet-y9boot-common-model"))

    api("com.fasterxml.jackson.core:jackson-databind")
    api("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml")
    api("com.fasterxml.jackson.dataformat:jackson-dataformat-properties")
    api("org.apache.commons:commons-lang3")
    api("org.slf4j:slf4j-api")
    api("org.springframework:spring-web")
    api("org.springframework:spring-context")
    api(libs.commons.io)
    api(libs.commons.httpclient)
    api(libs.alibaba.transmittable.thread.local)
    api(libs.jbcrypt)
    api(libs.jxls.poi)
    api(libs.poi.scratchpad)
    api(libs.hutool.all)
    api(libs.bcprov.ext.jdk18on)
    compileOnly("jakarta.servlet:jakarta.servlet-api")
}

description = "risenet-y9boot-common-util"
