server:
    port: 7056
    servlet:
        context-path: /y9demo-sso-oauth2
y9:
    feature:
        # 处理跨越问题
        security:
            enabled: true
            csrf:
                accepted-referer:
                    - youshengyun.com
                    - localhost
                    - 127.0.0.1
            cors:
                allowCredentials: true
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - http://localhost:8080
                    - http://localhost:8081
                    - http://localhost:7070
        oauth2:
            resource:
                enabled: true
                allowBasicAuthentication: true
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                protectedUrlPatterns: /*
                opaque:
                    client-id: clientid_oidc
                    client-secret: secret_oidc
                    introspection-uri: http://localhost:7055/sso/oidc/introspect
                    profile-uri: http://localhost:7055/sso/oidc/profile
