spring:
    cloud:
        nacos:
            config:
                enabled: false
                namespace: local
                group: DEFAULT_GROUP
                server-addr: https://test.youshengyun.com
                username: nacos
                password: ${NACOS_PASSWORD:111111}
    config:
        import:
            - optional:nacos:log.yml