version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql01
    restart: always
    ports:
      - "3309:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'Y9i-83204585'
      MYSQL_DATABASE: 'y9_public'
    volumes:
      - d:/docker-data/mysql:/var/lib/mysql
      
  redis:
    image: redis:latest
    container_name: redis01
    restart: always
    ports:
      - "7379:6379"
    command: redis-server --requirepass "y9i-83204585"
    volumes:
      - d:/docker-data/redis:/data
      