spring:
    cloud:
        nacos:
            config:
                enabled: false
                namespace: local
                group: DEFAULT_GROUP
                server-addr: https://dev.youshengyun.com:443
                username: nacos
                password: Risesoft@2022
    config:
        import:
            - optional:nacos:platform.yml