spring:
    cloud:
        nacos:
            config:
                enabled: true
                namespace: dev
                group: DEFAULT_GROUP
                server-addr: https://dev.youshengyun.com:443
                username: nacos
                password: ${NACOS_PASSWORD:111111}
    config:
        import:
            - optional:nacos:platform.yml