spring:
    cloud:
        nacos:
            config:
                enabled: true
                group: DEFAULT_GROUP
                namespace: vue
                server-addr: nacos:8848
                username: nacos
                password: ${NACOS_PASSWORD:111111}
    config:
        import:
            - optional:nacos:platform.yml