spring:
    cloud:
        nacos:
            config:
                enabled: true
                namespace: vue
                group: DEFAULT_GROUP
                server-addr: https://vue.youshengyun.com:443
                username: nacos
                password: ${NACOS_PASSWORD:111111}
    config:
        import:
            - optional:nacos:fileManager.yml