spring:
    cloud:
        nacos:
            config:
                enabled: true
                group: DEFAULT_GROUP
                namespace: ${NACOS_NAMESPACE:prod}
                server-addr: ${NACOS_SERVER_ADDR:http://nacos:8848}
                username: ${NACOS_USERNAME:nacos}
                password: ${NACOS_PASSWORD:111111}
    config:
        import:
            - optional:nacos:fileManager.yml