spring:
    cloud:
        nacos:
            config:
                enabled: true
                namespace: test2
                group: DEFAULT_GROUP
                server-addr: nacos:8848
                username: nacos
                password: Risesoft@2024
    config:
        import:
            - optional:nacos:fileManager.yml