server:
  port: 9001

spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    #username: sa
    #url: jdbc:h2:mem:customdb;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:postgresql://localhost:5432/keycloak
    username: root
    password: "11111111"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: myrealm.json
