services:
    sso-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-webapp-sso:9.7.0-SNAPSHOT
        networks:
            - y9-share-net
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.sso-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) &&  PathPrefix(`/sso`)"
                - "traefik.http.routers.sso-v97x.service=sso-v97x"
                - "traefik.http.services.sso-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.sso-v97x.loadbalancer.server.port=8080"
    platform-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-y9platform:9.7.0-SNAPSHOT
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - y9-share-net
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.platform-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/platform`)"
                - "traefik.http.routers.platform-v97x.service=platform-v97x"
                - "traefik.http.services.platform-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.platform-v97x.loadbalancer.server.port=8080"
                - "prometheus.job=platform"
                - "prometheus.metrics-path=/platform/actuator/prometheus"
    log-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-log-jpa:v9.7.x
        networks:
            - y9-share-net
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.log-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/log`)"
                - "traefik.http.routers.log-v97x.service=log-v97x"
                - "traefik.http.services.log-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.log-v97x.loadbalancer.server.port=8080"

    addressbook-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-addressbook:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.addressbook-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-addressbook`)"
                - "traefik.http.routers.addressbook-v97x.service=addressbook-v97x"
                - "traefik.http.services.addressbook-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.addressbook-v97x.loadbalancer.server.port=8080"
    attendance-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-attendance:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.attendance-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-attendance`)"
                - "traefik.http.routers.attendance-v97x.service=attendance-v97x"
                - "traefik.http.services.attendance-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.attendance-v97x.loadbalancer.server.port=8080"
    calendar-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-calendar:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.calendar-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-calendar`)"
                - "traefik.http.routers.calendar-v97x.service=calendar-v97x"
                - "traefik.http.services.calendar-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.calendar-v97x.loadbalancer.server.port=8080"
    cms-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-cms:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.cms-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-cms`)"
                - "traefik.http.routers.cms-v97x.service=cms-v97x"
                - "traefik.http.services.cms-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.cms-v97x.loadbalancer.server.port=8080"
    contractmanage-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-contractmanage:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.contractmanage-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-contractmanage`)"
                - "traefik.http.routers.contractmanage-v97x.service=contractmanage-v97x"
                - "traefik.http.services.contractmanage-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.contractmanage-v97x.loadbalancer.server.port=8080"
    email-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-email:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.email-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-email`)"
                - "traefik.http.routers.email-v97x.service=email-v97x"
                - "traefik.http.services.email-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.email-v97x.loadbalancer.server.port=8080"
    y9home-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-home:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.y9home-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-home`)"
                - "traefik.http.routers.y9home-v97x.service=y9home-v97x"
                - "traefik.http.services.y9home-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.y9home-v97x.loadbalancer.server.port=8080"
    msgremind-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-msgremind:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.msgremind-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-msgremind`)"
                - "traefik.http.routers.msgremind-v97x.service=msgremind-v97x"
                - "traefik.http.services.msgremind-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.msgremind-v97x.loadbalancer.server.port=8080"
    todo-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-todo:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.todo-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-todo`)"
                - "traefik.http.routers.todo-v97x.service=todo-v97x"
                - "traefik.http.services.todo-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.todo-v97x.loadbalancer.server.port=8080"
    trainingtest-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-trainingtest:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.trainingtest-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-trainingtest`)"
                - "traefik.http.routers.trainingtest-v97x.service=trainingtest-v97x"
                - "traefik.http.services.trainingtest-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.trainingtest-v97x.loadbalancer.server.port=8080"
    useronline-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-useronline:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.useronline-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-useronline`)"
                - "traefik.http.routers.useronline-v97x.service=useronline-v97x"
                - "traefik.http.services.useronline-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.useronline-v97x.loadbalancer.server.port=8080"
    storage-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-storage:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.storage-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-storage/`)"
                - "traefik.http.routers.storage-v97x.service=storage-v97x"
                - "traefik.http.services.storage-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.storage-v97x.loadbalancer.server.port=8080"
    flowableui-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-y9flowableui:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.flowableui-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-flowableui`)"
                - "traefik.http.routers.flowableui-v97x.service=flowableui-v97x"
                - "traefik.http.services.flowableui-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.flowableui-v97x.loadbalancer.server.port=8080"
    itemadmin-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-y9itemadmin:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.itemadmin-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-itemadmin`)"
                - "traefik.http.routers.itemadmin-v97x.service=itemadmin-v97x"
                - "traefik.http.services.itemadmin-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.itemadmin-v97x.loadbalancer.server.port=8080"
    processadmin-v97x:
        image: docker-internal.youshengyun.com/v97x/risenet-y9boot-server-y9processadmin:v9.7.x
        networks:
            - y9-share-net
        environment:
            - TZ=Asia/Shanghai
            - SPRING_PROFILES_ACTIVE=test
            - NACOS_PASSWORD=Risesoft@@2024
            - JAVA_OPTS=-Xms512m -Xmx1500m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 2gb
                    cpus: '4'
                reservations:
                    memory: 2gb
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.processadmin-v97x.rule=(Host(`test2.youshengyun.com`) || Host(`test2-internal.youshengyun.com`)) && PathPrefix(`/server-processadmin`)"
                - "traefik.http.routers.processadmin-v97x.service=processadmin-v97x"
                - "traefik.http.services.processadmin-v97x.loadbalancer.passHostHeader=true"
                - "traefik.http.services.processadmin-v97x.loadbalancer.server.port=8080"
networks:
    y9-share-net:
        external: true