name: y9-dev-postgres-keycloak
services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka01
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - y9-share-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - /Users/dingzhaojun/docker-data/kafka/data:/mnt/shared/config
      - /Users/dingzhaojun/docker-data/kafka/:/etc/kafka/secrets
      - /Users/dingzhaojun/docker-data/kafka:/var/lib/kafka/data
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
  
networks:
  y9-share-net:
    external: true

# docker compose -f compose-kafka.yml up -d