version: '3.9'
name: y9-dev-environments
services:
  db:
    image: mysql:latest
    container_name: mysql01
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - y9-share-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'y9_public'
    volumes:
      - d:/docker-data/mysql:/var/lib/mysql
      - d:/docker-config/mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysql --user=root --password=12345678 --execute='show databases;'"
      interval: 5s
      timeout: 10s
      retries: 8
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
networks:
  y9-share-net:
    external: true
    
# docker compose -f compose-mysql.yml up -d