name: portainer
services:
  portainer:
    image: 6053537/portainer-ce:latest
    container_name: portainer
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - y9-share-net
    ports:
      - "9000:9000"
    volumes:
      - d:/docker-data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  y9-share-net:
    external: true