name: y9-ai-openwebui
services:
  openwebui:
    image: ghcr.nju.edu.cn/open-webui/open-webui:main
    container_name: openwebui
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - y9-share-net
    ports:
      - "3100:8080"
    environment:
      - USE_OLLAMA_DOCKER=false
      - OLLAMA_BASE_URL=http://host.docker.internal:11435
      - OPENAI_API_BASE_URL=http://model-runner.docker.internal:80/engines/llama.cpp/v1
      - OPENAI_API_KEY=na
    volumes:
      - d:/docker-data/openwebui:/app/backend/data

networks:
  y9-share-net:
    external: true
    
# docker compose -f compose-ai-openwebui.yml up -d