name: y9-dev-postgres-keycloak
services:
  db:
    image: mysql:latest
    container_name: mysql01
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - y9-share-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '11111111'
      MYSQL_DATABASE: 'y9_public'
      MYSQL_USER: admin 
      MYSQL_PASSWORD: '11111111'
    volumes:
      - d:/docker-data/mysql:/var/lib/mysql
      - d:/docker-config/mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysql --user=admin --password=11111111 --execute='show databases;'"
      interval: 5s
      timeout: 10s
      retries: 8
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
  postgresql:
    image: postgres:latest
    container_name: pg01
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - y9-share-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '11111111'
      POSTGRES_DB: 'keycloak-db'
    volumes:
      - d:/docker-data/postgres:/var/lib/postgresql/data/
      - d:/docker-config/postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      interval: 5s
      timeout: 10s
      retries: 8
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis01
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - y9-share-net
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: "--requirepass 12345678"
    volumes:
      - d:/docker-data/redis:/data
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
  keycloak:
    image: bitnami/keycloak:latest
    container_name: kc01
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - y9-share-net
    ports:
      - 8080:8080    
    environment:
      #KEYCLOAK_HOSTNAME: localhost
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 1
      
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: root
      KEYCLOAK_DATABASE_PASSWORD: 11111111
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_NAME: keycloak-db
    #command: start
    depends_on:
      - postgresql
      
networks:
  y9-share-net:
    external: true
    
# docker compose -f compose-keycloak.yml up -d