name: y9-mysql
services:
  mysql:
    image: mysql:latest
    container_name: mysql01
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - y9-share-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "11111111"
      MYSQL_DATABASE: "y9_public"
    volumes:
      - d:/docker-data/mysql:/var/lib/mysql
      - d:/docker-config/mysql-init:/docker-entrypoint-initdb.d
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
networks:
  y9-share-net:
    external: true
    
# docker compose -f compose-mysql.yml up -d