## STATIC CONFIGURATION
api:
  insecure: true
  dashboard: true
entryPoints:
  web:
    address: ":8081"
  traefik:
    address: ":8080"
log:
  level: INFO
  filePath: "/etc/traefik/logs/log-file.log"
  format: json
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false