spring:
    cloud:
        nacos:
            config:
                enabled: false
                namespace: ${NACOS_NAMESPACE:local}
                group: DEFAULT_GROUP
                server-addr: ${NACOS_SERVER_ADDR:https://dev.youshengyun.com:443}
                username: ${NACOS_USERNAME:nacos}
                password: ${NACOS_PASSWORD:111111}
    config:
        import:
            - optional:nacos:log.yml