/*
 * This file was generated by the Gradle "init" task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":y9-digitalbase-starter:risenet-y9boot-starter-openfeign"))
    api(project(":y9-digitalbase-module:y9-module-log:risenet-y9boot-api-interface-log"))
    compileOnly(libs.jakarta.servlet.jakarta.servlet.api)
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
}

description = "risenet-y9boot-api-feignclient-log"
