management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8080
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        session:
            tracking-modes: COOKIE
        context-path: /log
spring:
    application:
        name: log
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            # 需要使用 kafka 时注释掉让其能自动配置
            - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
    cloud:
        nacos:
            server-addr: https://test.youshengyun.com:443
            username: nacos
            password: ${NACOS_PASSWORD:111111}
            config:
                enabled: false
                group: DEFAULT_GROUP
                namespace: test
            discovery:
                enabled: false
                group: DEFAULT_GROUP
                namespace: test
    config:
        import:
            - optional:nacos:log.yml
            #- optional:nacos:test01.yml?group=group_02
            #- optional:nacos:test02.yml?group=group_03&refreshEnabled=false
    data:
        elasticsearch:
            repositories:
                enabled: true
    datasource:
        druid:
            filter:
                stat:
                    log-slow-sql: true
                    mergeSql: true
                    slow-sql-millis: 3000
                wall:
                    config:
                        drop-table-allow: false
                    enabled: true
            stat-view-servlet:
                enabled: false
                url-pattern: /druid/*
                login-username: admin
                login-password: admin
                reset-enable: false
                allow: 127.0.0.1
            web-stat-filter:
                enabled: false
                url-pattern: /*
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/static/*'
            y9-public:
                #driver-class-name: oracle.jdbc.OracleDriver
                #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
                #username: Y9_PUBLIC
                #password: '111111'
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/y9_public?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: 111111
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
    jpa:
        generate-ddl: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                hbm2ddl:
                    auto: none
                dialect: org.hibernate.dialect.MySQL8Dialect
                jdbc:
                    batch_size: 100
                show_sql: true
    elasticsearch:
        uris: localhost:9200
        username: elastic
        password: 'risesoft'
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-commit-interval: 1000
            enable-auto-commit: true
            group-id: y9log-server
    main:
        allow-bean-definition-overriding: true
    redis:
        database: 8
        host: localhost
        password: 111111
        port: 6379
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
            shutdown-timeout: 100ms
        ssl: false
        timeout: 10000
y9:
    systemName: ${spring.application.name}
    internalIp: 192.168.x.x,10.x.x.x,172.20.x.x
    app:
        log:
            #kafkaEnabled=true时才会初始化Kafka的事件监听（注意要将KafkaAutoConfiguration启用）
            kafkaEnabled: false
    service:
        org:
            directUrl: https://test-api.youshengyun.com
    common:
        kafkaEnabled: false
        logBaseUrl: https://test-api.youshengyun.com/log
        orgBaseUrl: https://test-api.youshengyun.com/platform
    feature:
        apisix:
            enabled: false
            adminAddress: http://localhost:9080/apisix/admin/
            adminKey: edd1c9f034335f136f87ad84b625c8f1
            upstreamType: roundrobin   #负载均衡算法，1、roundrobin:轮训 ; 2、chash:一致性哈希; 3、ewma:指数加权移动平均法; 4、least_conn:最小连接数
            #etcdAddress: http://localhost:2379  #有多个时逗号分隔
            apiBasePackages: net.risesoft #有多个时逗号分隔
            apiDomain: vue
        elasticsearch:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
        liquibase:
            public-enabled: true
        multi-tenant:
            # kafka, db
            event-source: db
        log:
            enabled: true
            # kafka, api
            reportMethod: api
        security:
            enabled: true
            csrf:
                accepted-referer:
                    - youshengyun.com
                    - localhost
                    - 127.0.0.1
            cors:
                allowCredentials: true
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - http://localhost:8080
                    - http://localhost:8081
                    - http://localhost:7070
                    - http://localhost:7071
            xss:
                ignoreParam:
                    - id
                    - userName
        oauth2:
            resource:
                enabled: true
                allowBasicAuthentication: true
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                protectedUrlPatterns: /admin/*
                opaque:
                    client-id: clientid_oidc
                    client-secret: secret_oidc
                    introspection-uri: http://localhost:7055/sso/oidc/introspect
                    profile-uri: http://localhost:7055/sso/oidc/profile