spring:
    application:
        name: y9public
    profiles:
        active: prod
    cloud:
        nacos:
            config:
                enabled: true
                namespace: vue
                group: DEFAULT_GROUP
                server-addr: https://vue.youshengyun.com:443
                username: nacos
                password: Risesoft@2022
    config:
        import:
            - optional:nacos:y9public.yml