server:
    port: 8080
    servlet:
        context-path: /y9demo-elasticsearch
spring:
    application:
        name: demo-elk
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    data:
        elasticsearch:
            repositories:
                enabled: true
    elasticsearch:
        uris: localhost:9200
        username: elastic
        password: 'risesoft'
        connectionTimeout: 5
    main:
        allow-bean-definition-overriding: true
y9:
    feature:
        elasticsearch:
            packagesToScanEntityPublic: net.risesoft.elastic.entity
            packagesToScanRepositoryPublic: net.risesoft.elastic.repository
