server:
    port: 8080
    servlet:
          context-path: /demo-file
y9:
    #系统名称，用于记录文件是哪个系统上传的
    systemName: demo-file
    feature:
        jpa:
            #数字底座文件上传的包的需要扫描的包路径，不能更改
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
        file:
            #是否对文件名 base64 编码
            base64FileName: false
            #是否用对称加密算法 AES 加密文件内容
            encryptionFileContent: false
            #对于不能动态扩容的存储空间 可以通过分目录挂新盘扩展存储空间
            #prefix:
            #私钥
            #privateKey: 
            #公钥
            #publicKey: 
            ftp:
              #是否启用
                enabled: true
                host: localhost
                port: 21
                username: y9admin
                password: '111111'
                blockWhenExhausted: true
                bufferSize: 10240
                connectTimeOut: 50000
                controlEncoding: UTF-8
                dataTimeout: 1200000
                fileType: 2
                maxIdle: 10
                maxTotal: 50
                minIdle: 2
                maxWaitMillis: 5400000
                testOnBorrow: true
                testOnCreate: true
                testOnReturn: true
                testWhileIdle: true
                useEPSVwithIPv4: false
                passiveMode: true
            local:
                enabled: false
                # 本地文件存储的根路径，按需设置为自己的
                basePath: "d:/y9FileStore"
spring:
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    #文件相关表信息需要的数据源信息，需要配置为数字底座的公共数据源
    datasource:
        druid:
            y9-public:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/y9_public?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: 111111
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
