server:
    port: 8080
    servlet:
          context-path: /demo-file
y9:
    #系统名称，用于记录文件是哪个系统上传的
    systemName: demo-file
    feature:
        jpa:
             #数字底座文件上传的包的需要扫描的包路径，不能更改
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
        file:
            base64FileName: false
            encryptionFileContent: false
            #privateKey: 
            #publicKey: 
            #ftp配置信息
            ftp:
                host: localhost
                port: 21
                username: y9admin
                password: '111111'
                blockWhenExhausted: true
                bufferSize: 10240
                connectTimeOut: 50000
                controlEncoding: UTF-8
                dataTimeout: 1200000
                fileType: 2
                maxIdle: 10
                maxTotal: 50
                minIdle: 2
                maxWaitMillis: 5400000
                testOnBorrow: true
                testOnCreate: true
                testOnReturn: true
                testWhileIdle: true
                useEPSVwithIPv4: false
                passiveMode: true
spring:
    #文件相关表信息需要的数据源信息，需要配置为数字底座的公共数据源
    datasource:
        druid:
            y9-public:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/y9_public?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: 111111
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
    #redis配置，主要用于雪花算法生成id
    redis:
        database: 8
        host: localhost
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
            shutdown-timeout: 100ms
        password: y9i-83204585
        port: 6379
        ssl: false
        timeout: 10000