idCode_url: https://api.idcode.org.cn
analyze_url: http://s.idcode.org.cn/
main_code: MA.156.1003.1629
api_key: 9XRMKN90QA8O90SDAAAAAKJ
api_code: 09DN09QA8X08XRNN9DRMXRXM9DNAK09Q
goto_url: http://s.idcode.org.cn/
sample_url: http://s.idcode.org.cn/