spring:
    application:
        name: y9public
    profiles:
        active: dev
    cloud:
        nacos:
            config:
                enabled: true
                namespace: dev
                group: DEFAULT_GROUP
                server-addr: https://dev.youshengyun.com:443
                username: nacos
                password: Risesoft@2022
    config:
        import:
            - optional:nacos:y9public.yml